name: pyjanitor-dev
channels:
- defaults
- conda-forge
- ericmjl
- rdkit
dependencies:
- python=3.6
- pandas
- pytest
- ipython
- ipykernel
- sphinx
- recommonmark
- pipreqs
- flake8
- xlrd
- missingno
- scikit-learn
- twine
- bumpversion
- pytest-cov
- pandas-flavor
- conda
- pylint
- biopython
- doc8
- rdkit
- pip:
  - sphinxcontrib-fulltoc
