steps:
  - script: |
      $(activate.command) pyjanitor-dev
      make lint
    displayName: 'Code style check: pycodestyle'
  - script: |
      $(activate.command) pyjanitor-dev
      black --check -l 79 .
    displayName: 'Code style check: black'
  - script: |
      $(activate.command) pyjanitor-dev
      make test
    displayName: 'Run all pyjanitor tests.'
  - script: |
      $(activate.command) pyjanitor-dev
      jupyter nbconvert --to notebook --config nbconvert_config.py --execute --template full
    displayName: 'Test that all notebooks execute correctly.'
    - script: |
      $(activate.command) pyjanitor-dev
      cd docs
      sphinx-build . _build/html -b html -W
    displayName: 'Test that HTML docs all build correctly.'